### ISSUE TITLE
Inventory Pets still disables flight from some mods

### ISSUE THREAD

**Issue by Jayv6** [capnkirok/Inventory-Pets#584] opened 2024-03-04 00:53 UTC
Forge 47.2.20
Inventory Pets 2.1 (1.20.1)
I have confirmed that two different mods that give flight (everlasting abilities and remorphed) have flight abilities and with inventory pets in it disables them

**Comment by Jayv6** [comment] 2024-03-04 01:14
Uh so I just tested it with just Those mods (remorphed everlasting abilities and inventory pets) and i have flight from the two i was tlaking about. But in all of the mods that i do have when i add inventory pets it disables flight but I dont know which one

**Comment by Jayv6** [comment] 2024-03-04 02:33
Apothesis causes this I am checking if any other mod does

**Comment by Kingdemonic666** [comment] 2024-03-04 04:12
If you use Re-Avaritia that is probably the cause.
versions 1.3.5 and 1.3.5.3 break survival flight for other mods.

**Comment by capnkirok** [comment] 2024-03-04 04:15
> Forge 47.2.20 Inventory Pets 2.1 (1.20.1) I have confirmed that two different mods that give flight (everlasting abilities and remorphed) have flight abilities and with inventory pets in it disables them

I tested: Identity, Morph, angel ring/curios, Fluegal tiara, Flight potion, Vampirism, Ars Nouveau.  I didn't test Everlasting Abilities, Remorphed, or Mystical Agriculture, but will do so next.

Let me know what you guys find out in your testing. Sadly, most of these have to be handled on a case-by-case basis.

**Comment by Luviam** [comment] 2024-03-06 20:56
The flight from the Gravitational Modulating Unit from Mekanism still doesn't work for me in 2.1

**Comment by stevnguy** [comment] 2024-03-07 12:27
Flügel tiara still doesn't work for me on with version 2.1 (1.20.1) 
Tested it on forge 47.2.20 with just Botania 443+dependencies and and inventory pets 2.1

**Comment by capnkirok** [comment] 2024-03-09 15:53
Thanks @stevnguy can confirm there was an issue with my Curios implementation. Angel Ring and Flugel Tiara now confirmed working in Dev. Fixing the rest of the list now.

**Comment by Diversion98** [comment] 2024-03-19 18:08
with Inventory Pets 2.1.1, its still not fixed with FTB Essentials 2001.2.2
Still can't use the /fly command when Inventory Pets is loaded ingame

**Comment by capnkirok** [comment] 2024-03-19 18:14
/fly was not on my list to fix. I'll have to add it to the exceptions.

**Comment by xXNinjaWarXx** [comment] 2024-03-30 19:41
> > Forge 47.2.20 Inventory Pets 2.1 (1.20.1) I have confirmed that two different mods that give flight (everlasting abilities and remorphed) have flight abilities and with inventory pets in it disables them
> 
> I tested: Identity, Morph, angel ring/curios, Fluegal tiara, Flight potion, Vampirism, Ars Nouveau. I didn't test Everlasting Abilities, Remorphed, or Mystical Agriculture, but will do so next.
> 
> Let me know what you guys find out in your testing. Sadly, most of these have to be handled on a case-by-case basis.

Is vampirism fixed?

**Comment by capnkirok** [comment] 2024-04-04 01:41
Please note that most mods now work properly on 1.20.1 with the exception of FTB Essentials /fly command.

For 1.18 and 1.19 versions, Curios implementations (Fluegal Tiara, Angel Ring) still need to be implemented.

**Comment by CraftyZombie** [comment] 2024-04-11 04:47
I believe Re:Avaritia's flight for Infinity Armor is also broken.

**Closed as completed** 2024-06-10 03:11 UTC
Labels: fixed in next release, compat, 1.20

**Comment by Tomperyeeter** [comment] 2024-10-21 17:41
Its odd, i got inv pets 1.20.1-2.1.3 and the cloud pet dont work or even /fly with ftb. But the weird thing is that
if i go to gamemode adventure, i can fly around with fly and pet but if i go back to survival it stops working. Thought i'd add that seems intressting!
