### ISSUE TITLE
Pet Naming Crash!

### ISSUE THREAD

**Issue by zzApotheosis** [capnkirok/Inventory-Pets#61] opened 2016-03-30 05:30 UTC
Java 8 Update 77 (64-bit)
MCP v9.05
FML v7.10.99.99
Minecraft Forge 10.13.4.1614
OptiFine_1.7.10_HD_U_D3
FastCraft 1.21

So it looks like the game crashes when I try to name my wither pet! The game calls the pet naming GUI and immediately crashes. It gave me [this crash report](https://drive.google.com/file/d/0B_wljXPJi507cWNXdERmV2J1LTg/view) on multiplayer. I tried it on single player, and it worked just fine.

I also just tried it on a fresh instance of a multiplayer server and it worked just fine... so I don't know exactly what could be causing this, but I'll leave this ticket here for reference anyway. Thanks for developing your awesome mod, by the way! ;)

**Comment by zzApotheosis** [comment] 2016-03-30 05:37
Well, after attempting to name different pets, it seems this issue has plagued me with all my pets... Unfortunate. I got the same crash when trying to name a magma cube pet too.

https://drive.google.com/file/d/0B_wljXPJi507S0F4WG44MFY2XzQ/view?usp=sharing

**Comment by capnkirok** [comment] 2016-03-30 21:02
Thanks @zzApotheosis for the report and the details. I will take look!

**Comment by capnkirok** [comment] 2016-03-31 05:13
Ok, did some testing, and I was unable to reproduce, but I did find a few threads with similiar issues, and a suggested fix. I will include this fix in the update coming out late today (version 1.4.1). Let me know if it works. I leave the issue Open until I hear back.

**Comment by zzApotheosis** [comment] 2016-04-01 07:03
Just tried it in 1.4.1. (Nice update by the way!) It still crashes :(

New crash report:
https://drive.google.com/file/d/0B_wljXPJi507X1piNDJoZ3AwaU0/view?usp=sharing

It's so strange, though, because it only crashes on my specific world/server. It's very late-game. This crash doesn't happen on new worlds or servers.

So you can see for yourself what happens: https://drive.google.com/file/d/0B_wljXPJi507WmpMWG91S0puZVU/view?usp=sharing

**Comment by capnkirok** [comment] 2016-04-02 06:03
Thank you for the details! I'll keep working on it and see what I can do.

**Comment by zzApotheosis** [comment] 2016-04-03 23:08
No problem! Also, I forgot to say that it's a client-only crash. The server is fine when the crash happens.

Currently, my workaround is to use NBTExplorer to directly edit the NBT tags of the pets and change their names that way lol

**Comment by capnkirok** [comment] 2016-05-03 19:15
Just curious.... have you tried this without Optifine? The error doesn't specifically mention inventory pets, though it could be that my gui is causing confusion... let me know.

**Comment by zzApotheosis** [comment] 2016-05-03 20:09
Hey, I'm at school right now but I'll try it without Optifine when I get home. It's weird because it crashes my very-end-game world (with Optifine) but in a fresh new world with the exact same modpack (with Optifine), it's fine. I'll experiment later and give you an update.

**Comment by zzApotheosis** [comment] 2016-05-04 03:23
Can confirm: Without Optifine, I get the same crash. However, it's worth noting that I transferred my server world to single player, so this new crash happened on single player without Optifine.

https://drive.google.com/file/d/0B_wljXPJi507a2NEWTFOSWxHVEk/view?usp=sharing

**Comment by capnkirok** [comment] 2016-06-08 20:09
Finally, I have made some progress here and have been able to recreate the issue. Working on a fix now.

**Comment by capnkirok** [comment] 2016-06-08 20:30
Yeeeessss..... this is fixed (FINALLY) in Dev.

**Comment by capnkirok** [comment] 2016-06-16 16:47
Fixed in 1.9 and 1.9.4 prior to launch

**Comment by capnkirok** [comment] 2016-06-18 13:26
Fixed in 1.7.10

**Closed as completed** 2016-06-19 15:11 UTC
Labels: bug, fixed in next release
