### ISSUE TITLE
Various localization issues

### ISSUE THREAD

**Issue by qznfbnj** [capnkirok/Inventory-Pets#542] opened 2023-06-28 03:16 UTC
Why can "Loading biomes..." be localized, but wolfName + " says there is a " + wolfName + " nearby." adn so on not? Is it because of the use of m_237113_()?

##  "Loading biomes..." 
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/390be44b-7d14-4ecd-b16c-d581ef02e034)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/5aa8109a-d524-48d6-9865-c1148402f175)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/f573ead6-71f2-4bb1-bfec-4053ea3239fe)

## wolfName + " says there is a " + wolfName + " nearby." and so on
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/a8d7f786-2f63-4e88-8af1-4ac3538219d0)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/38d1da41-3738-48fe-8acb-c85e6256d112)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/cb2efe78-4c9f-45b9-bb1e-da75981886d6)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/578db818-beb8-4e20-9b30-cb986c891eda)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/cf253adf-dfd2-47de-ab8d-020f8e45019c)

**Comment by capnkirok** [comment] 2023-07-01 15:21
No, it's because I forgot to update this Pet's localization. Marking as a bug.

**Comment by capnkirok** [comment] 2023-07-04 15:49
Ok, fixed the Biome Pet. Working on Wolf next. Wolf done.

**Comment by qznfbnj** [comment] 2023-07-04 16:32
## (1) Favorite Food
(1.1)
最爱的食物：黑曜石粒（Favorite Food: Obsidian Nugget）
`or` 下界石英（or Nether Quartz）
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/2fa94abc-5495-4a09-aaa5-081168c5022b)
(1.2) And is this line break optional?
(1.3) And the line break in GREEN tooltips of Anvil Pet / Nether Portal Pet / End Portal Pet?


## (2) Cooldown message
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/911e013e-ffe7-406f-83cb-4f82700e5fce)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/d273fe16-05df-4bc6-999d-971b8c0da35c)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/f43be9a2-3f8a-4654-ac67-0019a07de32d)

## (3) Petrifier
When there is no diamond in the inventory, there is no message feedback for using it on an inappropriate block.
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/61fd91f6-decd-4dea-8e37-08d5baea13b5)

When you have a diamond in your inventory, using it on a block will give you two feedback messages.
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/ea8860c4-76d1-4538-b097-6893e4076213)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/12e72ae3-394d-488d-a5e5-0fc030f2d3ec)

When there is no diamond in the inventory, using it on a mob will give you two feedback messages.
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/1044dc18-90a5-4c28-8d94-ca9fdf9b3793)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/004ad213-bc74-4b9e-a92f-e4d6e1cfd058)

## (4) Word order differences between languages
Current localization: `Suggested by` [nickname] -> `建议(Suggested) by` [nickname]
Suggested localization: `Suggested by [nickname]` -> `由(by) [nickname] 建议(suggested)`
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/06623e37-7888-4743-9208-34678f5481ca)

## (5) Translation about Pingot
This part is a trivial question: I wonder if `Pingot` stands for `Pet Ingot`? The current Chinese translation of Pingot is `声呐(sonar)`, do you think it fits this pet?
(5.2) Where is tooltip.ip.petpingot3?
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/d86b0aa7-fdf3-4731-a1da-07d77537d007)

**Comment by qznfbnj** [comment] 2023-07-04 16:38
and Cooldown message
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/911e013e-ffe7-406f-83cb-4f82700e5fce)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/d273fe16-05df-4bc6-999d-971b8c0da35c)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/f43be9a2-3f8a-4654-ac67-0019a07de32d)

**Comment by capnkirok** [comment] 2023-07-04 17:33
On 5) It's a combination of a Sonar "Ping" and "Ingot". Sonar works, I think as it explains the purpose.

**Comment by capnkirok** [comment] 2023-07-04 19:00
On 1) added 'or ' to lang file. Found in Nether Portal and End Portal pets.

String key is "tooltip.ip.or"

**Comment by capnkirok** [comment] 2023-07-05 11:44
On 2) I've added in several new strings to make this work for Illuminati:
"tooltip.ip.illuminaticooldown": " is on cooldown. ",
"tooltip.ip.illuminatiremaining": " remaining.",
"tooltip.ip.illuminatiseconds": " seconds",
"tooltip.ip.illuminatiready": " ready!",
"tooltip.ip.illuminaticonfirmed": " Confirmed!!",

**Comment by capnkirok** [comment] 2023-07-07 21:32
Also fixed Heart, Shield & Juggernaut, which all use some of the above cooldown strings

**Comment by capnkirok** [comment] 2023-07-07 21:41
Added new strings for Cobblestone and Dirt Pets:
 "info.cobble.notfound": "No Cobblestone Pet holder found in range!",
  "info.dirt.notfound": "No Dirt Pet holder found in range!",

**Comment by capnkirok** [comment] 2023-07-07 22:34
Fixed the dupe strings on the Petrifier.

**Closed as completed** 2023-07-07 22:43 UTC
Labels: bug, fixed in next release, 1.18, 1.19

**Comment by qznfbnj** [comment] 2023-07-08 17:29
2.0.19
## 1) Confirmed!!
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/39aa7efc-d099-4aa0-8651-ab3e42521857)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/ea7283df-b508-4ee2-909f-388375cab467)

## 2) Cooldown message
The current translation is a compromising translation for Illuminati pets, for other pets (Heart, Shield) that appear incongruous. Not bad for Juggernaut though.
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/c21b7785-5d9d-493a-ae8c-2ec6c3d9e6b6)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/3279dbf2-122d-417a-8ba7-a7e21c96a3fb)
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/455bb1f4-c009-4de0-8b3d-b9f1ee4cea8b)

## 3) Petrifier
Why are there two messages when use on a block without diamond?
![image](https://github.com/capnkirok/Inventory-Pets/assets/100760086/36bbae98-cf33-47f5-9af0-97e50dfb6315)
