### ISSUE TITLE
Feed bag, chest, double chest deletes items in creative mode on server

### ISSUE THREAD

**Issue by chessnut98** [capnkirok/Inventory-Pets#407] opened 2021-02-11 00:29 UTC
When switching to creative from survival (idk if any other gamemode does the same) with a feed bag in your inventory, the feed bag contents disappear. I'm on a server (unsure if it happens in singleplayer as well). I do have other mods running as well.

Version: Inventory Pets 2.0.11

**Comment by capnkirok** [comment] 2021-02-11 14:55
See also #394 

Hey @chessnut98 thanks so much for the report. This is so frustrating. It's the same code for the Chest Pets, which another player has reported the same issue, but I can't reproduce here. I've tested for hours on my server and it works fine, so I can only assume there's an event conflict with another mod. Can you tell me which mods you have installed?

**Comment by chessnut98** [comment] 2021-02-11 21:13
![Screenshot_1](https://user-images.githubusercontent.com/38761487/107699362-ff058700-6c83-11eb-84ed-dafe950a80a1.png)
Here are all my mods at the moment.

**Comment by capnkirok** [comment] 2021-02-12 21:26
Thank you so much! I've got reports on another modpack that has only 8 mods, so can use this for cross-reference. Going to try to tackle this this weekend.

**Comment by Kooramah** [comment] 2021-02-27 08:30
Thanks for looking into this @capnkirok, I just started to notice this yesterday and I've been using the latest version v2.0.12. Chicken pet seeds are gone :( LOL

**Comment by capnkirok** [comment] 2021-03-15 19:30
For everyone following this thread, I've had to do a complete rewrite of the inventory code. Hoping to have out by mid to end week (after more testing). The bug is actually in Minecraft, so had to rewrite from scratch.

**Comment by capnkirok** [comment] 2021-04-11 17:57
Finally got this one fixed in the 2.0.13 update. Please note, it will automatically update all Chests to a new version.

**Closed as completed** 2021-04-14 11:50 UTC
Labels: bug, fixed in next release, 1.15, 1.16
