### ISSUE TITLE
Minor Bug Version 1.20.1

### ISSUE THREAD

**Issue by YngFox** [capnkirok/Inventory-Pets#564] opened 2023-12-19 09:17 UTC
The pets eat whole items config when set to true doesn't change the in-game prompt to feed, it still says requires iron nuggets instead of iron bars for example. Not game-breaking for us by any means but I figured I would let the devs know in case they want to fix a minor bug.

**Comment by capnkirok** [comment] 2023-12-19 23:20
Not sure what you mean. This feature was introduced to make the food they eat harder to obtain. If you want to turn off eating, you should turn petsMustEat = false;

**Comment by capnkirok** [comment] 2024-01-13 17:19
Closing as this is working as intended

**Closed as completed by capnkirok** 2024-01-13 17:19 UTC
