### ISSUE TITLE
1.15.2 Saddle Pet Crash

### ISSUE THREAD

**Issue by willllcj** [capnkirok/Inventory-Pets#400] opened 2021-01-23 19:05 UTC
I'm sorry I don't have a lot of specifics or anything, it's my first time hosting a MC server. Whenever my friend is riding an animal with the saddle pet, my game crashes as soon as I hit the jump button. Their game doesn't crash, and the server stays up. I can try to provide any other details if needed. We tested with animals from vanilla and Better Animals Plus.

**Comment by capnkirok** [comment] 2021-01-23 21:57
Thanks for the note. If possible can you post your crash log to pastebin.com and then reply to this message with a link to the pastebin location? That will help tremendously.

**Comment by willllcj** [comment] 2021-01-24 21:08
Inventory Pets Crash - Pastebin.com <https://pastebin.com/xehimWSQ>

I think this is one of them, if you need more I think I should have a few
more of them.

**Comment by capnkirok** [comment] 2021-01-26 03:40
Thank you! This is perfect and I can see exactly where the problem is. There is something new in the 1.15.x - 1.16.4 codebase and how it treats Client Players on a server. I'll need to put in a fix.

**Comment by capnkirok** [comment] 2021-01-26 03:41
You can disable the Saddle Pet for now if you want until the fix is in.

**Comment by willllcj** [comment] 2021-01-26 16:48
Just making sure, this was in 1.15.2, were you saying that you fixed it in
1.16.4 and you're going to put it in 1.15.2?

**Comment by capnkirok** [comment] 2021-01-26 17:19
No, I wasn't clear. It's broken in both 1.15.x and 1.16.x (and I'll fix both!).

**Comment by willllcj** [comment] 2021-01-26 19:54
Ah, ok. Thanks for that, I'll keep an eye out for the update!

**Comment by capnkirok** [comment] 2021-01-29 21:53
Ok, this is fixed in Dev. Look for the release this weekend.

**Comment by willllcj** [comment] 2021-02-02 17:40
Is it on curseforge? Or just hadn't gotten it released yet? I'm not in a
hurry or anything I just didn't know if I was looking in the wrong spot.

**Closed as completed** 2021-02-07 22:24 UTC
Labels: bug, fixed in next release, compat, 1.15, 1.16
