### ISSUE TITLE
Inventory Pets Server Crash On Startup

### ISSUE THREAD

**Issue by Spudstak** [capnkirok/Inventory-Pets#457] opened 2021-06-02 14:58 UTC
Minecraft: 1.16.5
Forge: 36.1.23
Inventory Pets: 1.16.5-2.0.14

When I try to load up my modpack on my server Inventory Pets crashes. I don't really have a lot of information sorry.

[crash-2021-06-01_20.50.17-fml.txt](https://github.com/capnkirok/Inventory-Pets/files/6585461/crash-2021-06-01_20.50.17-fml.txt)

**Comment by capnkirok** [comment] 2021-06-02 15:03
There's enough info here, thanks. Looks like it's having trouble registering the Sea Cave dungeon. Likely a conflict with another mod. Will have to investigate. Thank you for posting.

**Comment by capnkirok** [comment] 2021-06-05 15:31
Well, it's definitely a conflict, and likely with one of your world gen mods. Unfortunately, I can't tell which. There's no reason that this should crash here, it's just registering the sea cave structure (like it has all the others). An out of bounds error (which is what this is), could only be caused by a limitation being added by one of your other mods. Do you have a link to your modpack?

**Comment by Spudstak** [comment] 2021-06-05 16:50
Yes, I do. https://www.curseforge.com/minecraft/modpacks/dimensions-dungeoneering/files

**Comment by Spudstak** [comment] 2021-06-05 16:50
It only crashes on the server side. On the client side it works completely fine.

**Comment by Spudstak** [comment] 2021-06-05 16:54
Also I should note. In order to run the modpack on the server side. You'll need to remove the following mods. Total Darkness, Structurize, Minecolonies, and possibly Voidscape. The reason for these are Total Darkness only works on the client side and currently Minecolonies sends packets that are too large.

**Comment by capnkirok** [comment] 2021-06-06 21:07
I'm not having any luck with this so far. Wild question... do any of your mods create any underwater structures in the Overworld?

**Comment by Spudstak** [comment] 2021-06-07 00:21
Yes, quite a few do I think. Off of the top of my head I think that When Dungeons Arise adds some, Dungeons Plus adds an underwater garden. Upgrade Aquatic adds some things to oceans, but I don't know if it adds structures tbh. Also Yung's better portals could be placed in oceans underground. Other than that I can't think of anything else, but there very well could be more...

**Comment by Spudstak** [comment] 2021-06-07 00:22
Ah also, Upstream adds modified rivers into the game and could very well mess with this type of generation too.

**Comment by Spudstak** [comment] 2021-06-15 23:34
Funny enough I can't seem to experience this error at all anymore... I ended up installing all of the files onto my server again from scratch and this doesn't happen.

**Comment by capnkirok** [comment] 2021-06-15 23:37
Oooh. I love these updates! Ok, I'll put this one aside for the time being. I'll leave it open for a few more days in case it crops up again.

Thank you for the follow-up!

**Comment by capnkirok** [comment] 2021-08-16 03:11
Closing as this appears to have fixed itself.

**Closed as completed by capnkirok** 2021-08-16 03:11 UTC
Labels: compat, investigating, 1.16
