### ISSUE TITLE
Mod breaks (Angel Ring) Flying on 1.19.2

### ISSUE THREAD

**Issue by ModernGamingWorld** [capnkirok/Inventory-Pets#598] opened 2024-04-20 22:24 UTC
The Age of Fate Owner and I did some testing and found out that this mod blocks just everything that has to do with flying. Like Mystical Agriculture Chest Plate with flight Augment, etc. We both do not want to remove this mod, but if you say you wont fix it, then we might not have a choice if its breaking all flying from other mods

**Comment by capnkirok** [comment] 2024-04-20 23:43
Are you using the 2.1.1 version on 1.19.2? There's a specific fix for Mystical Agriculture Chestplate (aka Supremium Chestplate). Is it not working for you?

This is a known issue and duplicate of #584. Of course I will fix it. It shouldn't break ALL flying... currently on 1.19.2 most flying should be fixed except for Curios-related flying (like Angel Ring). I recently implemented a fix using the Curios API on 1.20, which I've been testing and plan to move over to 1.19.2

**Comment by ModernGamingWorld** [comment] 2024-04-20 23:54
@capnkirok Age of fate owner was doing the test, I am just reporting what was found because it was the same problem on my modpack Monumental Experience. If its fixed then we can wait to test it then

**Comment by DexxKnight1** [comment] 2024-04-21 16:22
I did more testing and seems the Mystical Supremium and Awakened Supremium Chestplate works, but the Insanium Chestplate don't. The Flight Charm from Cyclic mod works, but Flight Potions don't. And the /fly command from the FTB Essentials mod doesn't work.

**Comment by capnkirok** [comment] 2024-04-22 13:49
@DexxKnight1 thanks for the follow up. Can you confirm what version of Minecraft you tested? 1.19 or 1.20?

**Comment by DexxKnight1** [comment] 2024-04-23 06:41
@capnkirok It's the version 1.19.2

**Comment by ModernGamingWorld** [comment] 2024-04-26 22:42
@capnkirok any update on this, I am holding off updating my next 1.19.2 version till its fixed

**Comment by capnkirok** [comment] 2024-04-27 00:43
Check back this Sunday evening. Work has been a bear this week.

**Comment by capnkirok** [comment] 2024-04-29 02:34
Some notes to @DexxKnight1:
- Flight Potion mod was not released on 1.19.2 (maybe you are talking about a different mod?)
- Insanium Chestplate is from Mystical Adaptations mod (an addon to Mythical Agricutlure). I've added this one, but just to let you know why it wasn't covered in the previous update.

**Comment by capnkirok** [comment] 2024-04-29 03:46
Ok, 1.19.2 has been updated. Please test and note that this now requires Curios API (5.1.6.1)

**Comment by ModernGamingWorld** [comment] 2024-05-01 16:27
@capnkirok I found another issue with the latest 1.19.2 version after I updated it. I keep getting this message in the game telling me there is a new version, whenever I am on the new version already.
![Screenshot 2024-05-01 112541](https://github.com/capnkirok/Inventory-Pets/assets/75923060/9e640871-276f-4e52-870f-004341674505)

**Comment by capnkirok** [comment] 2024-05-01 16:42
Yes, I didn't publicize the build yet, waiting to hear back on testing. I just need to flip a toggle on my server. Any other feedback?

**Closed as completed** 2024-05-07 16:22 UTC
Labels: fixed in next release, 1.19
