### ISSUE TITLE
Naming Bug

### ISSUE THREAD

**Issue by zzApotheosis** [capnkirok/Inventory-Pets#22] opened 2015-09-11 07:39 UTC
Seems that my pets lose their customized name when I right click with them! I'm guessing that's a bug. :P

Minecraft 1.7.10
Inventory Pets 1.3.2

**Comment by capnkirok** [comment] 2015-09-11 08:31
Hmmm... can't reproduce. Which Pet? Were you in a modpack or any other mods? Creative or Survival?

**Comment by zzApotheosis** [comment] 2015-09-11 18:21
Here's a clip of the bug: https://drive.google.com/file/d/0B_wljXPJi507dlVsaWhFamJxaTQ/view?usp=sharing

Note: The bug has happened to me with Magma Cube and Pingot. I haven't tested with any other pets.

Here's the (relatively small) modpack I used: https://drive.google.com/file/d/0B_wljXPJi507OGdXeWVhYm80RTQ/view?usp=sharing

**Comment by capnkirok** [comment] 2015-09-11 19:52
Thanks for the video, much appreciated :+1:

**Comment by capnkirok** [comment] 2015-09-11 22:19
Crud. Even with your modpack, can't reproduce. More questions: are you on a server? And not that it should matter, but which resource pack are you using...might as well check? (nice modpack, btw)

**Comment by zzApotheosis** [comment] 2015-09-11 23:34
Yeah, it's a mini pack I made for me and my lady. I usually play with a lot more than that, but it's still a neat pack :P

Anyway, I'm at work right now so I can't hop on to test, but I can tell you that I did indeed test on a server, and that video clip was taken on the server.

And I'm using a custom resource pack mostly based on Faithful. I'll send when I get home.

**Comment by zzApotheosis** [comment] 2015-09-12 06:03
Alright, here's my resource pack: https://drive.google.com/file/d/0B_wljXPJi507SkxLMWZoUmpDcDQ/view?usp=sharing

Let me know when you have it because I don't want to leave the link publicly active.

**Comment by capnkirok** [comment] 2015-09-12 06:09
Cheers. I got it :) Thanks for your thoroughness. I'm guessing it's a server issue :)

**Comment by zzApotheosis** [comment] 2015-09-12 08:38
Not a problem! I understand how frustrating it is when somebody's like "my miencarft crashez when i git wood!!11"

**Comment by capnkirok** [comment] 2015-10-13 23:53
Finally closing this one today. It was a weird one. It only affected 'active items' that did something on right click. Passive Pets (e.g., Sheep), were just fine. Ended up having to set the name again after whatever action was done (e.g., fireball, lighning, etc.)

**Closed as completed** 2015-10-13 23:53 UTC

**Comment by capnkirok** [comment] 2015-11-02 22:54
Just one last update.... Looks like this still wasn't working consistently on servers. I finally figured out how to implement packets and now the issue will be closed.
