### ISSUE TITLE
[1.16.4] Double chest pet issues 

### ISSUE THREAD

**Issue by RubGoose** [capnkirok/Inventory-Pets#394] opened 2021-01-14 16:19 UTC
So, i've ran into a very annoying and frustrating issue, where the double chest pet now acts as a trashcan...
It has deleted all items from itself and continues to do so. I've lost a lot of valuable items because of this.

Before it began, i had accidentally dropped it. I then could get to it and had to use creative mode. When i got it back and looked in it, all of the stuff was gone. I then rejoined the server i was on. Then i added some of the items back that i could remember and teleported home. To my surprise, it was all gone again

Could please fix it or find a way to do so.

**Comment by capnkirok** [comment] 2021-01-14 17:18
That is not good. The chest shouldn't lose its contents when you drop it (as it's stored on the item). I'll do some testing and see if I can find anything. Please let me know if you run into any other patterns, or if it occurs on other items in the meantime.

**Comment by RubGoose** [comment] 2021-01-15 11:38
Me and my friend have been searching for a pattern and found out that the issue is the switch between gamemodes. We've got a backpack mod installed as well, which seems to keep the items through change of gamemode.

**Comment by capnkirok** [comment] 2021-01-15 14:17
Thank you so much for the additional detail @RubGoose, super helpful.

**Comment by capnkirok** [comment] 2021-01-23 22:01
Hey @RubGoose I'm really stumped on this one. I've tested for about two hours and haven't seen any items disappear after switching game modes. I've also tried dropping the chests, dying, throwing chests, all while switching game modes, and so far no problems. I may try to install the backpack mod and see if there's a conflict somewhere (as you mentioned that you also have that installed). Do you have any other mods installed?

**Comment by Howlingwolf1011** [comment] 2021-02-09 01:14
Just to give a bit more info, i had an identical issue, saw that it was not just the (normal) chest pet whos inventory vanished, but also the inventory of a backpack added by another mod. Assumed as first it had nothing to do with the mods that gave me the inventories in question, but some other conflict, however i ran into this page by googling the issue. 

This is how to replicate the issue as we found it:
have an inventory item in your inventory (chest pet as an example)
have something in its inventory
go into creative mode
throw out a random item by dragging it into the JEI on the right side of the page
open inventory pet to discover its now empty, the item(s) vanished without a trace.

I was using the "Magitech Mana and Artifice" mod pack with 8 custom mods added in (including this one)
removing this mod alone fixed the issue with the other inventories for both me and the host of the world.

(apologies if me joining in on this issue instead of making a new one was the wrong thing to do, but sense it seems these may be the exact same issue i thought it was best)

**Comment by capnkirok** [comment] 2021-02-11 14:57
Thanks for the details. I will download the modpack and see if I can identify the issue. I have been unable to reproduce with just Inventory Pets on its own on the server.

**Comment by capnkirok** [comment] 2021-02-20 22:28
After much testing, I've narrowed down the issue, this does appear to be a bug in Inventory Pets and is not another mod conflict. 

It only happens in Creative mode on a Server environment, and is easily replicated by moving your feedbag, chest, or double chest to another slot in the hotbar. If you do this to any one of these items, it will clear the contents of any feedbags, chests, or double chests in your inventory.

Again, only in Creative and only on Server. Now that I can replicate I can trace back and find the source.

**Comment by Howlingwolf1011** [comment] 2021-02-21 01:51
Glad to help! I wish you luck on the bug hunt :D

**Comment by capnkirok** [comment] 2021-02-27 21:55
Well, I have an update, but it's not a great one. Though reported in 1.12, there is still evidently a known bug with Minecraft which is affecting Forge and unfortunately is still not fixed in any version of Minecraft: https://github.com/MinecraftForge/MinecraftForge/issues/4580

You'll see Botania, Baubles, and a few other mods had the same issue with their containers, but nothing could be done as it wasn't a priority for Minecraft. The only solution is to use a different method to store items instead of via Capabilities.

Until I can redo the functionality completely, I would avoid moving Chest or Feed Bag stacks when in Creative Mode when on a Server.

**Comment by capnkirok** [comment] 2021-03-15 19:32
Rewrote from scratch and finally testing a new version this week. Hope to have up by Friday.

**Comment by capnkirok** [comment] 2021-04-11 17:57
Finally fixed this. See the 2.0.13 version, should be up today.

**Closed as completed** 2021-04-14 11:50 UTC
Labels: bug, fixed in next release, 1.15, 1.16
