### ISSUE TITLE
Illuminati pet ignores blacklist

### ISSUE THREAD

**Issue by watchers0** [capnkirok/Inventory-Pets#609] opened 2024-07-27 03:19 UTC
Forge 47.3.0
Inventory Pets 2.1.2 (1.20.1)

I was playing a small custom modpack and I noticed the illuminati pet flat out ignored the blacklist in the config. I blacklisted quark and other mods but have gotten items from those mods from the pet. I even got air from the pet before even though it's blacklisted by default.

![image](https://github.com/user-attachments/assets/a0aea6de-886c-49a9-bc92-c40507731418)
![image](https://github.com/user-attachments/assets/4f807bcd-7629-4de5-ac0c-b7d179617be4)
![image](https://github.com/user-attachments/assets/148b18ec-1444-46a0-9a4d-825565c113f5)

**Comment by capnkirok** [comment] 2024-08-27 09:23
Thanks for the report. Won't be able to look until mid-September, just as an FYI.

**Comment by capnkirok** [comment] 2024-09-16 14:04
Confirmed this is a bug. Something must have gone wrong with one of the updates as I haven't changed this code since 1.12 version.

**Comment by capnkirok** [comment] 2024-09-18 13:41
Sure enough, Mojang changed the method so the correct data was not coming back. Ok, this is fixed in Dev on 1.20, look for it in a release before end of September.

Thanks for the detail!

**Closed as completed** 2024-10-02 16:31 UTC
Labels: bug, fixed in next release, 1.19, 1.20
