### ISSUE TITLE
Fly for other mods not working | Angel rings mod and Mystical Agriculture

### ISSUE THREAD

**Issue by buddyog01** [capnkirok/Inventory-Pets#581] opened 2024-02-26 17:07 UTC
I saw in another bug report that you said you added a .JSON file that allows other mods with fly capabilities to work but I can't find it in my server config files.

None of the angel rings in the Angel Ring mod work due to the cloud pet. I disabled the cloud pet fly ability, and the cloud pet entirely in my server config files and I still can't get fly with the Angel ring mod to work

Also I put the Flight Augment from Mystical Agriculture on my chestplate and it won't allow me to fly either. Not sure what to do because I disabled the cloud pet fly and the Cloud pet entirely and fly for any other mods don't work. Also like I said I can't find the .JSON you said you'd add to allow mods with fly abilities to work.

Mod Version: Latest 1.20.1
Minecraft Version 1.20.1

**Comment by buddyog01** [comment] 2024-02-26 17:16
Also I just realized I disabled the cloud pet and cloud pet fly in my server config files and the cloud pet is still craftable and still works completely fine

**Comment by capnkirok** [comment] 2024-03-02 20:46
This is a duplicate of #566

**Comment by capnkirok** [comment] 2024-03-03 20:10
For the record, I found a different way to do this for most Mods and using Curios' API.

**Closed as completed** 2024-03-04 00:32 UTC
Labels: duplicate, fixed in next release, 1.18, 1.19, 1.20
