### ISSUE TITLE
[1.16.x] Cloud pet not allowing flight / Squid Pet corrupting player data

### ISSUE THREAD

**Issue by entitybacca** [capnkirok/Inventory-Pets#537] opened 2023-06-21 18:36 UTC
Have a server in 1.16.5 and inventory pets is installed no configs are disabling the pet yet flight doesn't work with it, the flying saddle pet does work however.

**Comment by capnkirok** [comment] 2023-06-21 19:47
Are you using 2.0.18 version (the latest)?

**Comment by entitybacca** [comment] 2023-06-21 22:15
I am using the latest version aswell using the squid pet corrupts player data

**Comment by capnkirok** [comment] 2023-06-22 03:32
Confirmed that the Cloud Pet isn't working. I don't understand what you mean... "squid pet corrupts player data"...

**Comment by entitybacca** [comment] 2023-06-22 13:38
In my server when you have the squid pet in your hand and are in water your player data will get messed up and to log back in the player data (UUID) needs to be deleted.

**Comment by capnkirok** [comment] 2023-06-22 13:57
Thanks. Ok, so in server environment. Do you have any other mods installed? The squid pet shouldn't affect Player Data, so I'll have to dig in a bit more.

**Comment by entitybacca** [comment] 2023-06-22 21:33
yeah i have quite a few mods installed but i cant think of any that would affect that

**Comment by capnkirok** [comment] 2023-06-23 03:09
Ok, fixed the Cloud Pet issue (in dev). Investigating Squid now.

**Comment by IvvyDevMC** [comment] 2023-07-01 09:18
Squid bug happened on my server too, no other mods that affect water / effect in any way and the pet had to be disabled to fix the bug (deleting the playerdata obviously worked too)

**Comment by capnkirok** [comment] 2023-07-01 15:19
Thanks guys. This is super annoying, I'm sure. I'll have a fix for this rolled out this weekend.

**Comment by Diamond923** [comment] 2023-07-04 02:47
Hello, Is there any update to fix this issue? Experiencing the same thing

**Comment by capnkirok** [comment] 2023-07-04 03:14
Check tomorrow afternoon. Still working out some kinks, but should be ready.

**Comment by IvvyDevMC** [comment] 2023-07-04 15:26
> Squid bug happened on my server too, no other mods that affect water / effect in any way and the pet had to be disabled to fix the bug (deleting the playerdata obviously worked too)

Turns out, changing the position "fixed" the bug. Even if it is disabled, players still get locked out of the server whenever they are touching water. This exact same behaviour applies to the sheep pet.

**Comment by capnkirok** [comment] 2023-07-04 17:11
@AaronDevMC what do you mean the same behavior applies to the sheep pet? There is nothing in the code associating the Sheep Pet and Water. Are you saying when you hold the Sheep Pet in water, log out, then log back in, you see the same problem?

**Comment by IvvyDevMC** [comment] 2023-07-04 17:31
When utilitizing the slow Fall Effect, at seemingly random Points the Same Effect can be witnessed, tho the cause will be another. I Just mentioned it because the "Symptoms" are the Exact Same

**Comment by capnkirok** [comment] 2023-07-04 18:22
Alrighty, I've just uploaded a new version, 2.0.19. Check it out and let me know.

**Comment by capnkirok** [comment] 2023-07-04 18:49
If you guys experience issues, please paste any error logs you receive here.

**Closed as completed** 2023-07-04 18:54 UTC
Labels: bug, fixed in next release, 1.16
