### ISSUE TITLE
Cloud Pet disables other flight options (via double-tapping spacebar) when in inventory (not hotbar)

### ISSUE THREAD

**Issue by Aliishgi** [capnkirok/Inventory-Pets#403] opened 2021-01-30 16:06 UTC
When holding the cloud pet in your inventory (not in the hotbar), it appears you couldn't double-tap spacebar to fly anymore.
I've been testing the mod for a modpack I'm creating and encountered this bug. The reproduction rate seems to be 100%. At first, I thought it was a compatibility issue, and while it is, it also disables flight in creative mode of normal Minecraft. To fix it, you could simply remove the cloud pet from your inventory. This has been tested in the latest 1.12.2 version of the mod as of writing (v2.0.10).

**Comment by capnkirok** [comment] 2021-01-30 22:48
Thanks for the report, I'll check it out.

**Comment by capnkirok** [comment] 2021-01-31 22:59
Confirmed this is a bug in 1.12 only. Working on fix.

**Comment by capnkirok** [comment] 2021-01-31 23:09
Found the cause. Ok, this will be fixed in next release.

**Comment by Aliishgi** [comment] 2021-02-01 05:16
Wow, you're really fast! It's really cool watching an avid modder go through the steps in fixing something he/she is passionate about, and this isn't even talking about the fact you managed to do it in 2 days! It was a pleasure, and I'm looking forward to playing your mod.

**Closed as completed** 2021-02-07 22:24 UTC
Labels: bug, fixed in next release, 1.12
