### ISSUE TITLE
Flying and hitting shift will pull you to the ground

### ISSUE THREAD

**Issue by JamesSkullBlood** [capnkirok/Inventory-Pets#224] opened 2018-02-01 04:59 UTC
So first off I am here once again.
okay so anyways, I cannot pick the height of my flying.
Example: You are flying with the cloud pet in your inventory and you hit shift, to go down a bit, but not wanting to go all the way to the ground.

Now whenever you hit shift while flying with the cloud pet in inventory you will fall to the ground instead of staying flying.

If you are in Gamemode 1 you can hold down Shift+SpaceBar and you will stay hovering.
If you are in Gamemode 0 with the cloud pet in inventory and you press Shift you will fall to the ground instead of staying in the air.

I hope this makes sense.
One last time to make sure you get what I mean so this will get fixed soon.
If you are in GM1 while flying you are able to pick the height without falling down completely.
If you are in GM0 with Cloud pet in inventory and flying and you try to pick a height you will fall down completely.

Thanks again for making this mod, this mod is really fun to play with.

I also tested to make sure it was indeed this mod and not a conflict and it was this mod.
Hopefully this get fixed soon.
I hope I don't have to make anymore issues with the cloud pet
I am so sorry you have to see my terrible visual image. I decided right when I sent this issue it should have a visual image to see it better then my weak explanations.

![screenshot_64](https://user-images.githubusercontent.com/35322531/35661990-42bcca38-06db-11e8-8401-14a1b1d6a0a8.png)

**Comment by JamesSkullBlood** [comment] 2018-02-01 21:30
OH yeah the version is the newest version the 1.12-1.4.9.9b

All you need to do is to hit shift while in mid flight with the cloud pet in inventory. (It was late last night when I was typing this issue so my explaining was so bad)

**Comment by JamesSkullBlood** [comment] 2018-02-08 23:01
I am now able to shift without falling off the edge but now whenever I am flying with the cloud pet, and I accidentally hit shift key I will fall to the ground.

**Comment by capnkirok** [comment] 2018-02-09 15:45
Hey @JamesSkullBlood this is working fine for me. Can you test without other mods and let me know if you see the same? (my guess is a conflict with another mod that provides flight)

**Comment by JamesSkullBlood** [comment] 2018-02-09 23:59
Just got done testing it with ONLY the Inventory Pet mod version 1.12-1.4.9.9b and it is indeed the Inventory Pet mod.
In the 1.4.9.9a I was able to hold down shift without it even taking you fully to the ground.
In the 1.4.9.9b I accidentally hit shift and I saw myself falling, I DIDN'T die, but just accidentally hitting shift will take you to the ground and not keeping you in fly mode. It kinda like if you are already flying and you hit the SpaceBar Twice to go to the ground so you don't have to keep holding down shift.

I hope that made sense.
Remember I am now able to shift while on edges.
It just whenever I am flying and hit shift on accident it will take me to the ground unless I double press SpaceBar to stay in the air.

**Comment by capnkirok** [comment] 2018-02-12 15:56
OK, maybe I need to test with latest version of Forge. When I hit shift in my dev space, the player stops going down once I release (as it did before).

**Comment by JamesSkullBlood** [comment] 2018-02-16 05:54
Found out anything yet?

**Comment by JamesSkullBlood** [comment] 2018-02-19 23:25
I hope you can find out something soon.

**Comment by capnkirok** [comment] 2018-02-19 23:47
Working on other things at the moment @JamesSkullBlood . Plus I have a job and family and things. Will get around to it, though :)

**Comment by JamesSkullBlood** [comment] 2018-03-17 17:23
Hey, anything new?

And I understand you have a job and family, since real life comes first.

**Comment by capnkirok** [comment] 2018-03-21 07:03
No update yet. Still not able to reproduce...

**Comment by JamesSkullBlood** [comment] 2018-03-21 12:49
Weird. Maybe you might have mess something up when you was fixing my first issue I made the one where you cannot shift on edges with a cloud pet in your hot bar/inventory.

Have you tried using the latest version of forge? If not, when you do, go over lava with the cloud pet in your hot bar while in survival mode, make sure you are flying and just hit shift 1 time and see if you don't go into the lava.

**Comment by JamesSkullBlood** [comment] 2018-04-14 23:32
Maybe you already fixed it without knowing you did and just need to release another update to this mod.

**Comment by JamesSkullBlood** [comment] 2018-04-28 21:22
Still nothing I see, like I said, maybe do some other fixes for this mod release another update and hope it was fixed?

**Comment by melbellrocks** [comment] 2018-05-26 23:08
This is also happening to me.  First noticed while playing FoolCraft 3, so I created a singleplayer world with ONLY inventory pets and it's still doing it.  FC3 uses forge version 14.23.3.2673, but I also tested with the latest version of Forge.  Also using the latest version of Inventory Pets, 1.12-1.4.9.9b

While flying with the cloud pet if you hit shift you just fall out of the sky.

I just checked the problem does not occur in version 1.12-1.4.9.9a.  In that previous version it behaves as expected, you descend while holding shift and stay in the sky when you release shift.

**Comment by JamesSkullBlood** [comment] 2018-05-27 06:05
I am sooo glad it wasn't just me, I understand the maker of the mod is busy, but I wished he reply again.
Hoping like crazy it will get fixed in the next update.

**Comment by capnkirok** [comment] 2018-05-30 21:05
Yeah, this will be fixed in the next release. Also referenced in #232

**Comment by JamesSkullBlood** [comment] 2018-05-30 21:38
Thank you, I saw your reply on that one, sorry if I seem to annoying about this. Thanks for the reply and getting it fixed soon.
Looking forward to the next version.

**Closed as completed** 2018-06-17 21:01 UTC
Labels: 1.7.10, fixed in next release
