### ISSUE TITLE
Silverfish Pet doesn't work.

### ISSUE THREAD

**Issue by wiarrri** [capnkirok/Inventory-Pets#455] opened 2021-05-30 09:44 UTC
Each time I tried to use it, the console wrote about saving chunks of every dimension.
![image](https://user-images.githubusercontent.com/85027636/120099536-6d982300-c155-11eb-87f5-ba8df35a15d8.png)

**Comment by capnkirok** [comment] 2021-05-30 15:13
This means you have a crash somewhere. Go into your minecraft folder, copy the 'latest.log' file and paste it here, so I can see what's causing the crash. 

Also let me know what version of Minecraft and Inventory Pets you are using.

**Comment by wiarrri** [comment] 2021-05-31 10:23
Here.
[latest.log](https://github.com/capnkirok/Inventory-Pets/files/6569586/latest.log)
The version is 2.0.14. Sorry for being slow.

**Comment by capnkirok** [comment] 2021-06-05 13:22
Well, after testing, it's not crashing, but it doesn't seem to work consistently in Single Player (non-server). So, marking as a bug.

**Comment by capnkirok** [comment] 2021-06-05 14:00
Ok, I found the issue, it was a client/server desync. Caused by some bad code written by me! It will be fixed in the 2.0.15 version, due to release tomorrow (June 6).

**Closed as completed** 2021-06-06 22:48 UTC
Labels: bug, fixed in next release, 1.12, 1.15, 1.16
