### ISSUE TITLE
Ocelot pet inventory problem

### ISSUE THREAD

**Issue by Frobuzmumber** [capnkirok/Inventory-Pets#80] opened 2016-06-05 22:20 UTC
_edit_ found out that the squid pet also does this.
The ocelot pet causes the client to leave the server with a "Connection lost" "Internal server error" whenever it is taken from the hotbar and placed into inventory, or if it is picked up directly to inventory and not placed in the hotbar. I have posted my logs both client and server and have a video that I was recording during this event if you need it. I will continue to test the pets without testing the ocelot. 
-Frobuzmumber (Andrew)
Forge version: forge-1.9.12.16.1901
Server
Mods: Inventory pets 1.4.6 Beta, JEI 3.3.3.197
Latest log file:
Client: [2016-06-05-2.log.gz](https://github.com/capnkirok/Inventory-Pets/files/299539/2016-06-05-2.log.gz)
Server: [fml-server-latest.zip](https://github.com/capnkirok/Inventory-Pets/files/299537/fml-server-latest.zip)

---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 10586 (10.0.10586.0)

CPU:total 8 (8 cores per cpu, 1 threads per core) family 21 model 2 stepping 0, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, aes, clmul, mmxext, 3dnowpref, lzcnt, sse4a, tsc, tscinvbit, tscinv, bmi1

Memory: 4k page, physical 8364712k(2844568k free), swap 23044776k(12879380k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.91-b14) for windows-amd64 JRE (1.8.0_91-b14), built on Apr  1 2016 00:58:32 by "java_re" with MS VC++ 10.0 (VS2010)

time: Sun Jun 05 18:07:10 2016
elapsed time: 1598 seconds (0d 0h 26m 38s)

**Comment by capnkirok** [comment] 2016-06-06 14:57
Thanks, it makes sense as they share the same logic, likely having to do with the timing of the removal of Night Vision from the player. Good detail, thanks!

EDIT: Ha ha. This was caused by a leftover compatibility fix for Gem Armor with EE2 from 1.7.10. I have removed this, and this is now fixed in Dev.

**Closed as completed** 2016-06-11 13:26 UTC
Labels: bug, fixed in next release
