### ISSUE TITLE
Cow Pet; Fake Milk

### ISSUE THREAD

**Issue by PiordaNautor** [capnkirok/Inventory-Pets#330] opened 2019-10-16 20:05 UTC
Sometimes when a bucket of milk is filled (whether it is a singular or a stack of buckets) by a Cow Pet, attempting to move or separate the bucket(s) in your inventory will revert them into empty buckets.

**Comment by capnkirok** [comment] 2020-03-14 00:32
I am not able to reproduce this problem, on client or server. Do you have any other mods installed? Can you tell me what version of MC and Inventory Pets you are using?

**Comment by capnkirok** [comment] 2020-03-24 01:25
Did another round of tests, and am still unable to reproduce. Closing.

**Closed as completed by capnkirok** 2020-03-24 01:25 UTC
Labels: question, investigating

**Comment by EchoingZen** [comment] 2020-10-20 05:46
I know this issue is closed but I'd like to leave a message here just in case anyone runs into this issue.
Quitting and reentering will not resolve the fake milk. You need to quit the game completely and relaunch it. It should fix it up.

Version I was using: inventorypets-1.12-2.0.6.jar (Part of the "Uncle Genny's 100% Organic & Free-Range Modpack")

Apologies if posting this here wasn't appropriate :)
