### ISSUE TITLE
1.10 Client crash

### ISSUE THREAD

**Issue by Xobias** [capnkirok/Inventory-Pets#101] opened 2016-07-16 01:17 UTC
After crafting an anvil pet and giving it some food I was kicked back to the server list and the only message is in the server console is the below:

`java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;`

However after a server reboot I am able to get back on the server OK but have deleted the pet in case it keeps happening. I do have tools from Tinkers Construct and a blade from SlashBlade unsure if there is any incompatibility with these mods.

**Comment by capnkirok** [comment] 2016-07-16 05:43
Thanks for the report Xobias, and for the additional mods. I saw this report about the 'Living Anvil' on 1.7.10, not 1.10 though. Was this error on 1.7.10 or 1.10? And was the anvil in your hotbar, or out in the world? Thanks.

EDIT: Your post helped me narrow it down and figure out, so thank you!

**Comment by capnkirok** [comment] 2016-07-16 06:48
This is fixed in dev, will be released today. Duplicate of #89 .

**Closed as completed by capnkirok** 2016-07-16 06:48 UTC
Labels: duplicate
