### ISSUE TITLE
Illuminati Pet removes recipes?

### ISSUE THREAD

**Issue by binarybagel** [capnkirok/Inventory-Pets#106] opened 2016-07-30 02:22 UTC
# I am not sure whether this is a feature or a bug, but every item given by the Illuminati Pet becomes uncraftable. If this is a feature, please tell me how to undo it.

Modpack: Material Energy Ex

Version: As far as I know the most recent.
Minecraft Version: 1.10.2

**Comment by capnkirok** [comment] 2016-07-30 07:13
Ok, I can confirm that this is a bug. So bizarre. If you are wondering about the details, it's because I was actually taking the crafting recipe output itemstack, converting it to an entityitem, and spawning it into the world. Making a copy of the output itemstack prevents the bug from happening. It appears that 1.9.4+ something changed.

This is fixed in dev, and I will put out an update this weekend. 

By the way, you can temporarily fix this by restarting client/server.

Nice one.

**Comment by binarybagel** [comment] 2016-07-30 11:00
Thank you! Apparently this means the server I played on was never restarted...

**Comment by capnkirok** [comment] 2016-07-30 12:36
Interesting that you can manipulate the output recipes of even vanilla items. I will have to keep this in mind for the future 👍

**Closed as completed** 2016-08-01 21:29 UTC
Labels: bug, fixed in next release
