### ISSUE TITLE
Issue with 1.7.10

### ISSUE THREAD

**Issue by mkrtes** [capnkirok/Inventory-Pets#194] opened 2017-07-22 14:56 UTC
When I use mod on server, I do not see the pets tab in creative-mode. Inventory search work normally. 
Also, I see the error in the console when player entering.
Server core is Thermos-1.7.10-1614

Error: https://pastebin.com/eZs1qMbf

**Comment by capnkirok** [comment] 2017-07-28 11:30
Must be a conflict with Thermos. This has never been reported before...

The error on the console is Thermos preventing Extended Properties from loading.. can't explain that one. Have you asked the Thermos folks? EP is working just fine on other servers and with other mods.

**Comment by capnkirok** [comment] 2017-09-27 08:33
Hi, I'm closing this one as the mod is working as intended from our side (and in multiple modpacks). Please let us know if you find the answer.

**Closed as completed by capnkirok** 2017-09-27 08:33 UTC
Labels: 1.7.10, compat, investigating
