### ISSUE TITLE
Change pets to store timers on nbt - remove global cooldowns

### ISSUE THREAD

**Issue by RacerDelux** [capnkirok/Inventory-Pets#98] opened 2016-07-07 04:22 UTC
I am not sure how many pets do this, but the illumaniti pet (for example), when used, will trigger a global cool down for any player with said pet. Is this by design? I know for our server it is somewhat annoying.

This can be fixed by checking the cool down based on NBT and not storing the cool down on the item itself.

**Comment by capnkirok** [comment] 2016-07-07 04:33
Duplicate of #53

**Comment by capnkirok** [comment] 2016-07-07 04:35
It was originally by design. This was changed in 1.7.10, will roll it out to other versions next update.

For the record, will change Illuminati and Juggernaut. Will keep April Fool as is.

**Closed as completed** 2016-07-18 00:03 UTC
Labels: duplicate, fixed in next release
