### ISSUE TITLE
Quiver Pet No Infinite Arrows while passive with food

### ISSUE THREAD

**Issue by P-rox-y** [capnkirok/Inventory-Pets#414] opened 2021-03-01 11:05 UTC
Wanted to get some clarification on the Quiver Pet. 

Currently I only get infinite arrows when right clicking, or "active", and that's it. 

When the pet is in the hotbar passively with feathers in inventory my bow/arrows act as normal and I only have a limited amount (whatever I'm carrying at the time). When I shoot my last arrow, I get no additional arrows from Quiver pet. Nor does it look like I get arrows passively. 

Issue #381 which was version referenced a change in the Mojang logic making shot arrows to be recoverable which introduced a need for Quiver pet to have new functionality in regards to populating new arrows when we run out (we won't always be able to recover our arrows). 

The new functionality was referenced as to be added in the next release which I assume meant 2.0.12 however being on .12 now it doesn't seem to have that new functionality introduced yet, nor does the changelog reference quiver pet at all. 

So is this new functionality coming in .13? or was it released on .12 but still having issues?

MC: 1.16.5
Ver: inventorypets-2.0.12

**Comment by capnkirok** [comment] 2021-03-14 15:48
Hey @P-rox-y looks like this is working inconsistently in the current version. If the pet has just been fed and you are out of arrows, and then you try use your bow... an arrow will magically appear. Other times... it doesn't work at all. This is not what was intended. Working on a fix now.

If you run out, it's supposed to give you a new arrow (no questions asked, as long as the Quiver Pet is well fed).

**Comment by capnkirok** [comment] 2021-03-14 16:47
Ok this is fixed in the next release, and works as originally intended:

If you run out of Arrows (all types), it will give you a new basic arrow, as long as the Quiver Pet is well fed.

**Comment by P-rox-y** [comment] 2021-03-15 06:44
Thank you!

**Closed as completed** 2021-04-14 11:50 UTC
Labels: bug, fixed in next release, 1.15, 1.16
