### ISSUE TITLE
infinite life from blood magic and inventory pets

### ISSUE THREAD

**Issue by Brakat07** [capnkirok/Inventory-Pets#103] opened 2016-07-25 05:19 UTC

**Comment by Brakat07** [comment] 2016-07-25 05:22
Issue Description:

you can't die (sorry for my bad English)

What happens:

i was just sacrificing blood for my altar and i lose all my hearts and die so i hit respawn and i spawned in the same location (next to the altar) but my bed is 50 block away from my BM area and your character become so glitched and if you do that 5 times you can't even move and your screen become so shaky

and if you do /kill it dose the same thing fall damage fix it and go to main screen fix it

What you expected to happen:

i think it was inventory pets mod by Purplicious_Cow

i was using heart pet and Purplicious cow pet for regeneration

Steps to reproduce:

get your heart pet (inventory pets)
get your Purplicious cow pet (inventory pets)
sacrifice your blood to the altar ...

and i did tell wayoftime this glitch and he tell me 
Cannot reproduce with just Blood Magic. Honestly, this sounds like a glitch that must be taken up with Inventory pets. Try dying by other means.

and if you die you still regenerate your to full

**Comment by Brakat07** [comment] 2016-07-25 05:29
![2016-07-25_08 27 03](https://cloud.githubusercontent.com/assets/19719327/17091303/e6073b4c-5241-11e6-9dbb-91062960f3e6.png)
![2016-07-25_08 27 19](https://cloud.githubusercontent.com/assets/19719327/17091304/e60e3212-5241-11e6-8709-4f704d49d148.png)
![2016-07-25_08 27 21](https://cloud.githubusercontent.com/assets/19719327/17091305/e641b7ea-5241-11e6-9559-1636b6ac5f35.png)
![2016-07-25_08 27 23](https://cloud.githubusercontent.com/assets/19719327/17091306/e647da26-5241-11e6-8325-3bb259c815cc.png)

**Comment by capnkirok** [comment] 2016-07-25 17:18
Will take a look, thanks.

**Comment by Brakat07** [comment] 2016-07-26 05:01
thank you

**Comment by capnkirok** [comment] 2016-07-31 08:37
Well, I can confirm that approx. 1/10 times, the player can get stuck in some kind of limbo. It doesn't seem to happen all of the time. Respawning seems to fix it. 

It does register as a death (check your statistics), so there's no infinite life.

Will continue to test. Please note, I am only testing with Inventory Pets and Blood Magic, so please let me know if you have other mods.

**EDIT:** Ok, after more testing, I do not see a problem using the basic altar. Deaths are registering properly. And respawn at full health is normal after death. It can become shaky occasionally, but that's due to player positioning on top of the altar. Will try again with the advanced altar.

**EDIT:**  And tried with the more advanced altar, too. Not seeing the issue. The deaths are counting as deaths.

**Comment by Brakat07** [comment] 2016-07-31 12:23
I have 
blood magic 
inventory pets 
ender io 
storage network 
tinker construct 
woot 
progressive automaton
im very sorry that all I can remember because I deleted my save world the mod list so that all I can remember so just to tell I have 30 mod I think in that world
oh I remember 
torcherino 
ender utilities
dark utilities
optifine
rf tools
book shelf api
mcjity api
reborn core
ender core 
fast leaves decay
deep rec I don't now how to spell this word
elec core

**Comment by Brakat07** [comment] 2016-07-31 12:38
and I have tiar 5 altar 1450000LP in the altar

**Comment by capnkirok** [comment] 2016-08-01 21:31
@Brakat07 , try out the 1.4.8.1 version and see if it still occurs. I made a small tweak to ensure the Purplicious Cow pet didn't heal after death. No idea if this will fix it or not, but worth a shot.

**Comment by Brakat07** [comment] 2016-08-03 05:42
im sorry I can't test it because laptop is broken so I cannot test if it work sorry fixing it in 3 days so sorry

I sending this message from my phone

**Comment by capnkirok** [comment] 2016-08-03 20:23
No worries :)

**Comment by capnkirok** [comment] 2016-08-09 22:33
Another submission re: the purplicious cow leads me to believe there's something odd happening with the custom regen... it appears to be healing the player after he dies on the server, but before the client side can register it as a death. I've already put in a fix for this and will roll out in 1.4.8.2.

**Comment by Brakat07** [comment] 2016-08-27 21:48
thanks

**Comment by capnkirok** [comment] 2016-10-15 20:13
Fixed in both 1.10 and 1.7.10

**Closed as completed by capnkirok** 2016-10-15 20:13 UTC
Labels: bug, 1.7.10, fixed in next release, compat
