### ISSUE TITLE
Torch Pet Can Replace Blocks

### ISSUE THREAD

**Issue by WenXin20** [capnkirok/Inventory-Pets#299] opened 2019-03-18 02:15 UTC
Forge v14.23.5.2821-1.12.2
Inventory Pets v2.0

The torch pet can replace blocks that aren't normally replaceable, like a fence. It can be seen easily by right-clicking in the same block space as the fence.

**Comment by capnkirok** [comment] 2019-03-23 23:42
Hmmm... I'm not able to reproduce. When I do it, nothing happens (except the Torch pet eats, which is no good either). I'll keep trying.

**Comment by capnkirok** [comment] 2019-03-23 23:48
Ok, I made a change similar to the way bonemeal works, so that it if the the block is not normally replaceable, it places it on the closest block that is. 

This will be in 2.0.1 update.

**Comment by WenXin20** [comment] 2019-03-24 00:03
I had tried the torch pet out in creative, maybe that was why?

**Comment by capnkirok** [comment] 2019-03-24 00:07
Maybe, but you helped catch a bug anyway. Thanks !

**Comment by WenXin20** [comment] 2019-03-24 00:27
No problem!

**Closed as completed** 2019-03-24 19:32 UTC
Labels: bug, fixed in next release, 1.12
