### ISSUE TITLE
Not sure if you are aware of this

### ISSUE THREAD

**Issue by brisingraerowing** [capnkirok/Inventory-Pets#213] opened 2017-10-22 05:14 UTC
IP version: 1.4.9.9a
MC: 1.12.2

The beach pet 'dungeon' appears all throughout oceans as well, with one approx. every 5-10 chunks.
![2017-10-22_01 12 25](https://user-images.githubusercontent.com/250409/31858475-4dc571d8-b6c6-11e7-9449-76ab9ed4065c.png)

I don't think that was intended.

I use Biomes O' Plenty, BTW. That may have something to do with it.

**Comment by capnkirok** [comment] 2017-10-22 07:14
Yeah, that seems too high. I don't think it's BOP, just an oversight. Thanks!

**Comment by capnkirok** [comment] 2017-10-22 07:15
Oh, until I can get in a fix, you can turn down the frequency in the config  manually :)

**Comment by capnkirok** [comment] 2018-01-29 21:39
This is updated in the next release 
Dupe of #216

**Closed as completed** 2018-01-31 23:09 UTC
Labels: 1.7.10, fixed in next release, 1.12
