### ISSUE TITLE
Cloud Pet Compat Issues

### ISSUE THREAD

**Issue by LenartSvetek** [capnkirok/Inventory-Pets#26] opened 2015-10-17 17:15 UTC
When i try to fly does not.

**Comment by capnkirok** [comment] 2015-10-17 20:15
Hey Azmi1. Nothing wrong with the Cloud Pet. May be some other conflict though with another mod. Can you tell me what version of IP you are using, if there are any other mods installed (and what they are), and if you are on a server or just client? Also, just making sure, they are not hungry, right?

**Comment by LenartSvetek** [comment] 2015-10-19 12:03
i use inventory pet 1.7.10-1.3.5 mods                                                                                             (better furnace,bonesandstones,treecapitator,am2,4space,abyssalcraft,adventurepack,aether,animalsplus,       animationapi,applemilktea2,appliedenergistick2,balpkons weapon,bdlib,betterfps,bibliocraft,bloodmagic,bluepower,buildcraft,cars and drives,chocolate quest,codechickencore,companions,damege indicator,deep sea diving,dinosaour dimension,dimensional anchor,essence of gods,fastcraft... and many more)look if is in here problem if is not i will write others. I run on singleplayer so client.

**Comment by capnkirok** [comment] 2015-10-25 20:51
Azmi1, I tried a few of these and had no problem. However, you can help. Do any of these mods provide a 'flying in survival' type of buff (or anything to do with flying). I'm sure that's where the conflict is. We had a similar issue with Extra Utilities a couple of months ago.

**Comment by heyimcloudepet** [comment] 2015-11-02 08:42
capnkirok there  is still a problem with the cloud pet and the Extra Utilities mod and the cloud pet won't let me fly

**Comment by capnkirok** [comment] 2015-11-02 22:55
Hmmm.... we did fix this before. Maybe something changed recently.

**Comment by capnkirok** [comment] 2015-11-03 00:06
heyimcloudpet, just tried with Inventory Pets 1.3.5 and ExtraUtilities 1.2.12 and had no problems. Tried all of the rings and the Cloud worked fine. Which version of IP are you using? Are you on a server? Thanks for the help! We'll find out the problem eventually, I am sure, just need more data.

**Comment by heyimcloudepet** [comment] 2015-11-04 09:30
must be just me then

**Comment by capnkirok** [comment] 2015-11-04 18:06
@heyimcloudepet , any way you could send a screenshot of your installed mods? Same with you @Azmi1 ? I'd like to figure out what's going on if I can :)

**Comment by heyimcloudepet** [comment] 2015-11-07 20:21
![capture](https://cloud.githubusercontent.com/assets/15607491/11017119/ed038f00-85e0-11e5-9191-49c37d98f8cb.PNG)

**Comment by heyimcloudepet** [comment] 2015-11-07 23:54
![capture22](https://cloud.githubusercontent.com/assets/15607491/11017967/9c8bc2d6-85fe-11e5-8c60-c2c2af5a3257.PNG)
here ya go here is the mod list i am using

**Comment by capnkirok** [comment] 2015-11-08 14:45
Thanks for the modlist. The problem is with Survival Wings. I just took a look at their code and they seem to disable flight unless you are wearing their wings. Which is a problem. I've sent a message to spacechase0. Nothing we can do about it from our side.

**Comment by heyimcloudepet** [comment] 2015-11-08 20:11
oh ok i totally forgot i was using survival wings thanks for the help

**Comment by capnkirok** [comment] 2015-11-28 19:45
Survival Wings will be fixed in upcoming 1.8 release. No comment from the author on 1.7.10, sounds like it is not really supported anymore. Closing this issue.

**Closed as completed** 2015-11-30 21:27 UTC
