### ISSUE TITLE
Loot pet Occasionally stops/starts smelting.

### ISSUE THREAD

**Issue by Odentay** [capnkirok/Inventory-Pets#68] opened 2016-05-12 19:14 UTC
Have been playing on a server now for two weeks, and occassionally on a per player basis the Loot pet will stop smelting vanilla minecraft ores. There seems to be no direct cause on what causes it, it just seems to sometimes work, and other times not.

 Were on a crundeecraft server on a 1.7.10 mincraft version and a 1.4.3. for inventory pets. I know its not much to work off of, and may not be repeatable but it is getting rather frustrating

Thanks

**Comment by capnkirok** [comment] 2016-05-18 11:21
Odentay, any chance the players where it is not working are using an enchanted pickaxe? Otherwise, it seems like a conflict... I will look into it once I get your response.

**Comment by Odentay** [comment] 2016-05-18 14:39
Yes. Actually. The pickaxes are definetly enchanted.

**Comment by capnkirok** [comment] 2016-05-18 15:08
Loot Pet does not work with Fortune, Looting, or Silk Touch.

**Comment by Odentay** [comment] 2016-05-18 15:36
Ill double check the enchantments tonight afterwork. I got my pick off a
friend when he upgraded.

**Comment by kjj194** [comment] 2016-05-20 10:47
It appears that loot pet quits smelting upon breaking a block with a pick with either silk touch or fortune and does not begin smelting again when pick is removed from inventory. Removing mod and loading world is the only way I have found to clear the bug.

**Comment by capnkirok** [comment] 2016-05-20 11:21
Excellent detail! I think I can remedy this, now that the issue is clear. Next update is a couple weeks away.

**Comment by capnkirok** [comment] 2016-06-05 13:15
Ok, found the issue. It will be fixed in next update. Also, I'm going to add a message in user chat if they try to use the Loot Pet with an item that has Fortune, Looting, or Silk Touch.

**Comment by capnkirok** [comment] 2016-06-05 21:30
Fixed in Dev on all versions

**Comment by capnkirok** [comment] 2016-06-18 13:27
Fixed in 1.7.10, 1.9, 1.9.4

**Closed as completed** 2016-06-19 15:11 UTC
Labels: bug, fixed in next release
