### ISSUE TITLE
Chest Pets + Feed Bag (Randomly open other players pet chest inventory)

### ISSUE THREAD

**Issue by OldDogy** [capnkirok/Inventory-Pets#46] opened 2016-02-09 18:26 UTC
mod version: 1.7.10 - 1.3.91 ((EDIT: I just read how it was apparently fixed in 1.3.9 on all versions :P ))
This isn't the first time i ran in to this issue. First it was CrundeeCraft modpack, now Revenge of the C-Team.

As more players on the server get these Pets, all of a sudden you find your self opening someones pet chest inventory.

That's not all, you can take any item and keep it , while the owner never notices it's missing , because it actually somehow gets dupped. (Original player doesn't suffer item loss, while you can gain whatever they have in there pet chest inventory) and sometimes you can open there inventory multiple times and pull out same items multiple times.

I would love to at least know if anyone else ever had this issue. ( I suspect it happens if multiple people have the inventory open at the same time (unsure how the data is saved, so i can't understand where the issue is coming  from))

**Comment by capnkirok** [comment] 2016-02-09 22:34
Are you still having this issue on 1.3.91?? Revenge of the C-team was just updated, can you please verify? I don't see how this is possible with the latest version of Inventory Pets. The chest contents can only be opened by the owner now... 

I can verify myself that this has happened to multiple people (prior to 1.3.9).

**Comment by OldDogy** [comment] 2016-02-10 05:36
Yes 1.3.91 is when we noticed the issue.

I have tried testing it with another staff member on our server, cant figure out the cause. Happens sometimes if , I hold my chest open, and other player opens one , he either sees my content or his chest becomes fully empty. 
dropping the pet, and picking it up and switching it's hotbar location also leads to opening random chests sometimes. It is extremely random..

If you need me I can have the whole server do some testing. It could possibly be that save events overwrite somehow when multiple people have that inventory open? I really dunno i'm just wild guessing.

**Comment by capnkirok** [comment] 2016-02-10 07:56
Thanks OldDogy, really appreciate your help. It makes me sick to my stomach that it is still not fixed. I completely re-wrote the access and save code, and tested here with no errors. 

I'm thinking of creating a few test build with some screen logging to help me diagnose this latest  one. Would you mind testing a few builds for me in the next few days? I (and the rest of the IP community) would greatly appreciate it.

PC

**Comment by OldDogy** [comment] 2016-02-10 21:30
I can only try to imagine how you feel.
All I can do is, put up a local server, and harass some friends to help test it out :]

note: Revenge of C-Team is running on Thermos (which is honestly buggy, it  even caused issue with saving player ender chests correctly. (every time player logs of his ender chest would be deleted ) 

Dunno if that wrapper (thermos) could anyhow be the cause of the issue with your mod ?

But what i can do is, test current version on pure forge server, and then on thermos, see if it acts differently maybe?

I honestly don't know, I'm not a programmer, i don't code, I just try to think logically and connect the dots in any possible way. But what is happening here is really making me scratch my head. Thats why I would love to help in any possible way.

**Comment by capnkirok** [comment] 2016-02-10 21:44
Thanks, OldDogy! Yeah, that's weird stuff. I was able to replicate the problem on earlier versions of IP over local multiplayer server (playing with a laptop and my pc), but not after I changed all the code in 1.3.91.

The way I replicated it before was to repeatedly open, shift contents, and close a chest while a co-player repeatedly did the same. Eventually, either the chest contents disappeared, or shifted from one player to another. 

The old chest was using something called notify, which notifed the server that something had just happened with a chest and that it should update. The problem is if another person opens a chest after the notify, but before it's actually updated on the server (a millisecond or so), then the contents would get corrupted/and or transferred to this new chest. I no longer use notify, and instead the chest is saved on closing, and for sure, and tests only for that player. So, I'm really surprised by this.

What I'll do is create a couple of different builds with some tracking and send you a dropbox link, most likely Friday late. Any insight you can give is greatly appreciated.

**Comment by OldDogy** [comment] 2016-02-10 23:39
Good to know it saves on close. I've been struggling to find where it saves the data...
(not sure about this , but are you looking at your chest pets as bags ? or ? how did you imagine them?)

Got two people that are willing to help out. will maybe be able to  mess up the the save by all 3 of us closing the chests at the same-ish time, or two of us closing and one opening, we will see what happens.

But i'm wondering why are you saving each chest in separate file under player name ? or no ?  Something like what baubles inventory is doing ? Maybe look at your chest as an extended inventory , and the actual item would only be a link to opening that extended inventory....

(Bare with me I know nothing about how it all has to be done code sided, so i'm just mumbling here. But honestly i'm just hoping to give you an idea to look at the problem differently. )

I'll be around. Hopefully help you solve this one once and for all. (even tho i'm a complete noob when it comes to something like this ^-^ )

**Comment by capnkirok** [comment] 2016-02-14 07:04
Hey OldDogy -

I was able to replicate here in our test environment. It appears to occur when multiple chests are open at the same time, and one player closes after changing contents. It is not Thermos. Surprisingly simple to reproduce in 1.3.91, so things have not improved. Don't know why it didn't happen in earlier testing.

I don't have a solution yet, so I will continue working on it. I now believe the solution lies in grabbing the correct chest for the player, and how the chest is saved.

I've re-opened the original issue as well. I hope to have a solution in the next two days. Which I will send to you when ready.

PC

**Comment by capnkirok** [comment] 2016-02-20 09:41
Ok, have fully diagnosed the error. It is not random at all. Basically, when multiple players have a chest pet OPEN (of the same type), the player who closes the chest first overwrites the contents of all other OPEN chests. What's more, the chest then becomes a shared chest between players, and is no longer unique.

**Comment by capnkirok** [comment] 2016-02-20 14:34
OldDogy (or anyone interested) -

I have a Beta Build here, with a fix in for the Chest Pet (Please note that it does NOT include DoubleChest or FeedBag). There's lots of server logging as well, and it's not a public release. If you would like to test, please go ahead.

https://www.dropbox.com/s/p766ijkwonwbvfe/inventorypets-1.7.10-1.4.0-universal.jar?dl=0

EDIT: Much better, but still not working completely with brand new chests. Still working on it.

**Comment by capnkirok** [comment] 2016-03-02 20:16
Good News: I've completely rewritten the entire code from scratch and can confirm the chest, double chest, and feed bag will now work properly.

Bad News: I don't know how to upgrade old chests to the new model. So people will probably have to move all items out of their inventory pet chests to continue

**Comment by capnkirok** [comment] 2016-03-05 21:34
Ok, wrote new code to transfer contents from old chest to new chest when opened. This marks about 3 weeks of nonstop work on this bug. Now truly fixed in 1.4.0

**Closed as completed by capnkirok** 2016-03-05 21:34 UTC
Labels: bug, 1.7.10
