### ISSUE TITLE
All pets are not working

### ISSUE THREAD

**Issue by Brutis2** [capnkirok/Inventory-Pets#40] opened 2016-01-14 22:37 UTC
One i right click the Pets just disappear, Please help.
NOTE: I am using this on a server

**Comment by capnkirok** [comment] 2016-01-14 23:20
Hey Brutis2, 

This sounds like some kind of item conflict. Questions for you:
- What version of Inventory Pets are you using?
- What other mods are installed?
- Have you changed anything else on the server recently?

**Comment by Brutis2** [comment] 2016-01-21 02:27
1. Latest
2. No Other mods are installed
3. I havent changed anything.

**Comment by capnkirok** [comment] 2016-01-21 06:46
Ok that is totally bizarre. We've never seen something like this reported. There is nothing in the pets that stops them from working (unless they haven't eaten, of course. I assume you fed them?)
- What version of Forge are you using? And what version of MC?
- You might have corrupt data. A way to test this is to first back up your world, then create a new world and see if the problem persists.

**Comment by capnkirok** [comment] 2016-02-21 11:09
Closing issue as unable to reproduce and no other reports.

**Closed as completed by capnkirok** 2016-02-21 11:09 UTC
